### ISSUE TITLE
Put June scrape up on BigQuery

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/euctr-tracker-data#4]
In order to do the scoping for Tracey as well as have the recent data searchable, we need the June data put up on Bigquery.

**Comment by sebbacon** [comment]
https://bigquery.cloud.google.com/table/ebmdatalab:euctr.trials_2018_05_31?tab=preview

For future reference, I had to take the generated trials.csv, upload to Cloud Storage, then get a table from there.

**Comment by NickCEBM** [comment]
So this can obviously wait until next week but this isn't what I needed. 

The trails.csv is generated from this query: https://github.com/ebmdatalab/euctr-tracker-code/blob/master/euctr/euctr/management/commands/opentrials-to-csv.sql

What I need is the table that this query is drawing from. Basically it contains all the data elements for an EUCTR protocol entry, each one as its own column. This is what used to be available from OpenTrials back when we were still using redash.
